### Hello
GET http://api.valantis.store:40000 HTTP/1.1

### get_ids
POST http://api.valantis.store:40000 HTTP/1.1
content-type: application/json
X-Auth: 30fec2904fe148b7fe7cc5eeb3df9d6e

{
  "action": "get_ids",
  "params": {"offset": 10, "limit": 3}
}

### get_items
POST http://api.valantis.store:40000 HTTP/1.1
content-type: application/json
X-Auth: 30fec2904fe148b7fe7cc5eeb3df9d6e

{
  "action": "get_items",
  "params": {"ids": ["1789ecf3-f81c-4f49-ada2-83804dcc74b0"]}
}

### get_fields
POST http://api.valantis.store:40000 HTTP/1.1
content-type: application/json
X-Auth: 30fec2904fe148b7fe7cc5eeb3df9d6e

{
  "action": "get_fields",
  "params": {"field": "brand", "offset": 3, "limit": 5}
}

### filter
POST http://api.valantis.store:40000 HTTP/1.1
content-type: application/json
X-Auth: 30fec2904fe148b7fe7cc5eeb3df9d6e

{
  "action": "filter",
  "params": {"price": 17500.0}
}